name: Python Pipeline CI/CD

on: 
  push:
    branches:
      - CICD_pipeline  # Ejecuta solo cuando se hace push a la rama 'CICD_pipeline'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python hello.py

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: hello
          path: .
